apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registro-atividades
resources:
- namespace.yaml
- postgres-pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- api-deployment.yaml
- api-service.yaml
images:
- name: FelipeWippel/registro-atividades-backend
  newName: FelipeWippel/registro-atividades-backend
  newTag: latest
- name: wippel/registro-atividades-backend
  newTag: 2df8cf9e9be81e54dfe67031566b35908ac9fc34
